name: Build and Publish UF2s

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PICO_SDK_PATH: "${{ github.workspace }}/pico-sdk"

    strategy:
      matrix:
        board: [pico2_w, pico_w]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi

      - name: Set up Pico SDK
        run: |
          git clone https://github.com/raspberrypi/pico-sdk.git
          cd pico-sdk
          git submodule update --init

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DPICO_BOARD=${{ matrix.board }}
          make

      - name: Upload UF2
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.board }}-uf2
          path: build/pico_project_template.uf2