name: Build and Publish UF2s

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board: [pico2, picow]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Pico SDK
        run: |
          git clone https://github.com/raspberrypi/pico-sdk.git
          cd pico-sdk
          git submodule update --init
          cd ..
          export PICO_SDK_PATH=$(pwd)/pico-sdk

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DPICO_BOARD=${{ matrix.board }}
          make

      - name: Upload UF2
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.board }}-uf2
          path: build/pico_project_template.uf2
